### ISSUE TITLE
Error when running the bot

### ISSUE THREAD

**Issue by greyhat94** [bipinkrish/Save-Restricted-Bot#39]
I was trying to run the bot, and it gave me this error: 
```

Traceback (most recent call last):
  File "C:\Users\umile\Desktop\Tools\Save-Restricted-Bot-main\main.py", line 22, in <module>
    acc.start()
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\auth\connect.py", line 47, in connect
    await self.session.start()
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 142, in start
    raise e
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 109, in start
    await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\session\session.py", line 333, in send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.
```

How can I fix it?

**Comment by greyhat94** [comment]
Can someone help me to fix this error?
